### ISSUE TITLE
Game data type

### ISSUE THREAD

**Issue by jan-christiansen** [Frederik-Hamester/legislative-bargaining-lab#1]
Define a data type that is similar to the representation in JavaScript that can be used to represent vector-weighted voting games.

**Comment by Frederik-Hamester** [comment]
The Type can hold the 4 most simple test games.

**Comment by jan-christiansen** [comment]
Please clean up the code in `SimpleGame.elm`. Please use Caml-case for function names.

**Comment by jan-christiansen** [comment]
* What is the field `m` in the record `Player` used for? Rename please
* What is the field `n` in the record `SimpleGame` used for? Rename please
* Why does the constructor `BoolOr` take an additional `String` but `BoolAnd` does not?
* Instead of `takeReverse` you should use `drop` and `length`.
* coursed -> caused
* Due to the comment "removes artifacts coursed by undefined objects in js lists" at the function `cleanSimpleGame` I am wondering whether there is a cleaner way than using `takeReverse`. For example, actually removing "undefined" objects from the list by using `filter`.

**Comment by Frederik-Hamester** [comment]
1. field m is an artefact from the js SimpleGame object
2. field n represents the number of players in the simpleGame, it is now renamed playerCount
3. I am working on that
4. takeReverse is substituted with drop 
5. Is corrected 
6.  The artifacts are caused by the way the dictionary is realized in the js code.
    When the code parses a game, each player gets a new id by a counter. The first
    time the program is executed the counter is initialized with 1, then it counts
    up +1 for each new player. The weights of the players in the game rules, is
    stored in an array with the id as the index and weights as the value. In case a
    new game is parsed, the counter is not set back to 1, but instead it keeps the
    value from the previous parsed game. The artifacts we are dealing with, are
    caused by the offset of the counter. An artifact cells in the array, are empty
    Elm seems to decode an empty integer as 0. After the array has been decoded, the artifact cells can not be distinguished by player
    weights by their value since players can have a weight of 0 as well. My
    understanding of filter is that it distinguish List elements by its values. So I
    do not think filter should be used at this point. However, since it is known
    that the "legitimate" player weights in the array, are the last elements and the
    number of players is known, we can use "drop (arrayLength - playerNumber)" to
    remove the artifacts.
