### ISSUE TITLE
Check BuildRec algorithm in the paper

### ISSUE THREAD

**Issue by Frederik-Hamester** [Frederik-Hamester/legislative-bargaining-lab#12]
Some things about the BuildRec algorithm in the paper is unclear.
1. How is the lookup table used?
2. What are the two parameters of each node good for?

**Comment by jan-christiansen** [comment]
See the explanation right behind the proof of Proposition 4.8.

> This approach has the obvious shortcoming that it requires exponentially many re- cursive calls. As in the case of the knapsack problem, dynamic programming could be used to reduce the running time to something like O(nQ). The main idea for this ap- proach would be to store and reuse the return value of f for arguments i, q, because the algorithm returns the same Qobdd node for the same input. But, it sometimes returns the same node for different inputs as well. For example, consider the Wvgs [4;3,2] and [5; 3, 2]. Even though the quotas are different, the games have the same winning coalitions.
