### ISSUE TITLE
Define Decoder for Game Type

### ISSUE THREAD

**Issue by jan-christiansen** [Frederik-Hamester/legislative-bargaining-lab#2]
Define a Decoder that can be used to transform the JavaScript implementation of a game into the corresponding Elm representation.

**Comment by Frederik-Hamester** [comment]
Simple decoder that decodes the 4 most simple games. Most basic functionality. 
These is a extra button added to test the decoder. Pressing on button [Test parse game] decodes a game and prints it one the main display in string form.

**Comment by jan-christiansen** [comment]
Where is the definition of the decoder for a game. There should be a function of type `Json.Decoder SimpleGame`.

**Comment by jan-christiansen** [comment]
If I am not mistaken, you should remove the `String` argument from the `BoolOr` constructor. In the case of `BoolOr` you should parse the "kind" field but withdraw the additional argument, for example, using `\_ l r -> BoolOr l r`.

**Comment by Frederik-Hamester** [comment]
Removed the string from the BoolOr node in the JoinTree type in SimpleGame.elm

**Comment by Frederik-Hamester** [comment]
The decoder named simpleGameDecoder and located in SimpleGame.elm
