### ISSUE TITLE
Modular solution for identify JoinTree nodes

### ISSUE THREAD

**Issue by Frederik-Hamester** [Frederik-Hamester/legislative-bargaining-lab#5]
-remove js folder from repo.
- add string to BoolOr node in JoinTree with visitor.

**Comment by jan-christiansen** [comment]
Please remove the tabs from the JavaScript source files. In general you should never use tabs in source case.

**Comment by Frederik-Hamester** [comment]
Is fixed, forgot to set tabs to spaces in my editor.
