### ISSUE TITLE
Define a function of f SimpleGame -> QOBDD (for the moment without "sharing")

### ISSUE THREAD

**Issue by Frederik-Hamester** [Frederik-Hamester/legislative-bargaining-lab#6]
The function should generate a QOBDD without sharing and without giving sub trees IDs.

**Comment by Frederik-Hamester** [comment]
The function fromSGToSimpleQOBDD  in QOBDDBulders.elm can generate a QOBDD without sharing.

**Comment by jan-christiansen** [comment]
Please use ` before and after for function and module names in comments. This way a different font is used, which is more readable.

**Comment by jan-christiansen** [comment]
Please adapt the following
* the functions in `QOBDDBuilders` should use the comment style for functions
* `buildBDDWithIds` should use the player names as variables for the QOBDD
* in `fromSGToSimpleQOBDD` use pattern matching on the list instead of `head`

**Comment by Frederik-Hamester** [comment]
1. Comment style used in BOBDDBuilder.
2. I used the Player Id instead of the Player name. As long as the Elm code is dependent of the js SimpleGame object it seems better to use the id. The id is guaranteed to be unique the name has at the moment not that guaranteed and the Player in the js file is designed to use the id internally to identify a player. When we have more control about the generation of the SimpleGame object the player name could be used instead of the id. (This is something we can discuss at the next meating)
3. Pattern matching is used instead of the head function.
