### ISSUE TITLE
Add sharing to QOBDD function

### ISSUE THREAD

**Issue by Frederik-Hamester** [Frederik-Hamester/legislative-bargaining-lab#8]
Redefine the function that creates the QOBDD with ids, so that it creates a `Ref` node if the corresponding subtree already exists.

**Comment by Frederik-Hamester** [comment]
1. Renamed Id in QOBDD type to NodeId to prevent confusion with other types used as Ids.
2. Renamed `buildBDDWithIds`  to `buildBDD`.
3. Added sharing to `buildBDD`
   a) the EitherNodeId type is not so pretty but Either could not be used since it is not a comparable and 
        the type must be a comparable to be used as part of the key in a dictionary. However, maybe a 
        better definition can be used for the type.
   b) I found no error in the output of the function so fare, but checking even the more simple games is 
       quite tedious and error prone so there mite be some unspotted bugs.
   c) when trying the function on the two most complex games the browser freezes. I suspect that the 
       performance of the buildBDD function is still to bad for the browser.

**Comment by jan-christiansen** [comment]
* Wouldn't it be simpler to use the id `0` for the `Zero` sink and `1` for the `One` sink and use ids from `2` for all other nodes?
* I actually don't get why the type is called `Either`. The `Either` data type is a choice between two types, not a pair.
* While I understand you good intentions, please reduce the amount of comments. For example, you often repeat the type signature in the comment.

**Comment by Frederik-Hamester** [comment]
1. The NodeId is now used to express the id of a node or the it identifies the type of the leave. 
2. The type contains either the id of a node or the identity of a leave.
3. I reduced the comments.
