### ISSUE TITLE
What is the variable type in the QOBDD type in elm used for?

### ISSUE THREAD

**Issue by Frederik-Hamester** [Frederik-Hamester/legislative-bargaining-lab#9]
The Types corresponds with the field 'label' in the js qobdd

**Comment by Frederik-Hamester** [comment]
In the paper the label refers to a certain player or rather the positions of a player's weight in the weight vector. In the js qobdd it seems that the label expresses the same meaning. However, the players in the js simpleGame have an id, so I would expect that the ids are used instead of the position in the weight vector. In some situations the label in the js qobdd is infinite. Why is that the case?

**Comment by jan-christiansen** [comment]
Infinite is used for the leaves, that is, for the zero and one sink. In this case there is no "name"/label for the node. In summary the modelling of the QOBDD in JavaScript isn't that nice.
